### ISSUE TITLE
Countdown problem on Safari

### ISSUE THREAD

**Issue by pedluis** [fiedlr/timeLeft#1]
Hi, i'm using your plugin. It's really nice. I'm having problems on IOS devices. If you go for example to: https://www.ferrarisboutique.it/it/sandali/1252-sandalo-michael.html , there i've put my code. With chrome it works perfectly, even on mobile. But with safari, desktop/mobile i get immediatly the messagge of countdown finish(always even if the countdown is not end) and the worst is that the countdown is not visible. can you help me?
![image2](https://cloud.githubusercontent.com/assets/13334916/14600662/2e4e9dae-055e-11e6-8abf-40fd2f68e34d.PNG)

**Comment by pedluis** [comment]
As you can see the under the string Vuoi riceverlo Mertedi 19 aprile? should be present the countdown. can you help me?

**Comment by fiedlr** [comment]
Hi, thanks for your feedback.

Are you sure you have implemented it correctly? I just checked it on Safari Desktop & Mobile and everything seems to be working perfectly (I've uploaded it here to show you: [http://timeleft.fiedlr.io/test/](http://timeleft.fiedlr.io/test/))

Could you tell me what versions of Safari you use? And how you configured it? I wasn't able to find it with the link you've provided. Or just paste me the line where you work with timeLeft so that I could see it (like: `$('.countdown').timeLeft({ /* config */ });`)

Regards

**Comment by pedluis** [comment]
Thanks to you answer, yes but maybe i find the problem ( tell me if it
could be possible). I'm using it with prestashop, and it must be
dinamically, from sunday-till Friday the countdown must finish at 14:30 of
the next day, but on weekend must set to Monday. It could be possible that
all variables that I get with JavaScript to get the current date and to add
deadlines can be the problem? Now the countdown is inactive because I found
that even with edge and Mozilla mobile I get the same issue. What do you
think about?

Best regards

Pedro Trivino
El 18/04/2016 22:39, "Adam Fiedler" notifications@github.com escribió:

Hi, thanks for your feedback.

Are you sure you have implemented it correctly? I just checked it on Safari
Desktop & Mobile and everything seems to be working perfectly (I've
uploaded it here to show you: http://timeleft.fiedlr.io/test/)

Could you tell me what versions of Safari you use? And how you configured
it? I wasn't able to find it with the link you've provided. Or just paste
me the line where you work with timeLeft so that I could see it (like:
$('.countdown').timeLeft({
/\* config */ });)

Regards

**Comment by pedluis** [comment]
If you want I can reactivate it so you can see what I get

**Comment by fiedlr** [comment]
Well, it is possible that your input is formatted incorrectly. You might try reactivating it but the best would be if I could see the pasted code right here.

**Comment by pedluis** [comment]
Now it is active

https://www.ferrarisboutique.it/it/borse/1087-borsa-isobel.html

Check here, or in other product page of the Italian version. I've attached
two pictures one with chrome (working) an other with Mozilla (doesn't
work). If you want check the code that call your function is into the
pedro.js file.
El 18/04/2016 22:46, "Pedro Trivino" pedroluis.trivino@gmail.com escribió:

If you want I can reactivate it so you can see what I get

**Comment by fiedlr** [comment]
The problem is in how you format the input. See the console log - right now you're inputting:
`$('#gg-rimasti').timeLeft({till: ''+mese+' '+giorno+', '+anno+' 14:30:00', ...});`
which gives you
`$('#gg-rimasti').timeLeft({till: '4 18, 2016 14:30:00', ...});`
and this doesn't work with the Date object.

The string in the 'till' option has to be Javascript Date compatible. Check [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) for how to do it with number formatting.

**Comment by pedluis** [comment]
Sorry, but so i have to put the name of months instead of the number id?

Because i check but javascript accept numbers for month.

Pedro Trivino

2016-04-18 23:16 GMT+02:00 Adam Fiedler notifications@github.com:

**Comment by fiedlr** [comment]
Some of the examples of correct formats:

```
25 Dec 1995 13:30:00
2016-04-18 14:30:00
Apr 04, 2016 14:30:00
April 04, 2016 14:30:00
```

Therefore, in your case this might work:

`$('#gg-rimasti').timeLeft({till: anno+'-'+mese+'-'+giorno+' 14:30:00', ...});`

However, I'm not sure because I can't test it for you. Please refer to the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) link provided already.
